# Generated by Django 4.2.1 on 2023-05-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_ny',
            new_name='updated_by',
        ),
    ]
